# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

# Install build dependencies for shapely
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libgeos-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY pyproject.toml uv.lock src/ README.md ./

# Install the MCP server
RUN pip install --no-cache-dir .

# Default command for stdio MCP
CMD ["osm-mcp-server"]
